services:
    TCR.listener.audit:
      class: TCR\AuditBundle\EventListener\AuditService
      properties:
        container: '@service_container'
      tags:
        - { name: doctrine.event_listener, event: preUpdate }
        - { name: doctrine.event_listener, event: postFlush }

    TCR.auditviewer.service:
      class: TCR\AuditBundle\Service\AuditViewerService